import { createCarouselPresetProps } from '@margo/core';
import type { TenantFrontpageModel } from './frontpage';

export const demoFrontpage: TenantFrontpageModel = {
  tenant: {
    slug: 'bistro-frontpage',
    locale: 'en',
    displayName: 'Bistro Lumiere',
    enabledModules: ['frontpage'],
    themePresetId: 'editorial-bistro',
    layoutConfig: {
      nav: 'centered',
      navSticky: true,
      hero: 'full-bleed',
      contentWidth: 'wide',
      sectionRhythm: 'spacious',
      sectionBorder: 'thin',
      cardStyle: 'flat',
    },
    homeHref: '/t/bistro-frontpage',
  },
  page: {
    id: 'demo-home',
    tenantId: 'demo-tenant',
    slug: 'home',
    locale: 'en',
    title: 'Seasonal neighborhood dining',
    seo: { title: 'Seasonal neighborhood dining', description: 'Warm, seasonal cooking in the heart of the city.' },
    status: 'published',
    layoutPreset: 'editorial',
    services: [],
    locations: [
      {
        name: 'Bistro Lumiere',
        address: { street: '12 Rue Demo', city: 'Paris', country: 'FR' },
        phone: '+33100000001',
        email: 'hello@bistrolumiere.example',
      },
    ],
    blocks: [
      {
        id: 'hero',
        type: 'hero',
        variant: 'split-image',
        position: 0,
        props: {
          eyebrow: 'Public web',
          headline: 'Warm, seasonal cooking in the heart of the city.',
          body: 'A frontpage-only demo tenant showing white-label content and branding without booking or CRM links.',
          ctaLabel: 'View menu',
          secondaryLabel: 'Explore services',
          secondaryHref: '#services',
          panelLabel: 'Dining room',
          panelTitle: 'Refined, calm, and bookable',
          panelBody: 'A quieter editorial presentation that keeps content blocks fully customizable.',
          highlights: ['Seasonal menu', 'Local ingredients', 'Private dining available'],
          panelMeta: ['Open daily', 'Paris 2e'],
        },
      },
      {
        id: 'carousel',
        type: 'carousel',
        variant: 'cards',
        position: 1,
        props: createCarouselPresetProps('cards', {
          eyebrow: 'Highlights',
          title: 'Featured dishes and moments',
          body: 'A carousel preset for editorial highlights, promos, or collections.',
        }) as never,
      },
      { id: 'image', type: 'image', variant: 'cover', position: 2, props: { caption: 'A seasonal visual block.', imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80', buttonLabel: 'View gallery', buttonHref: '/gallery' } },
      { id: 'split-media', type: 'split-media', variant: 'image-right', position: 3, props: { title: 'Our approach', body: 'Fresh local ingredients, concise menus, and a calm dining room for neighborhood regulars.', imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80', buttonLabel: 'Book a table', buttonHref: '#contact' } },
      { id: 'rich', type: 'rich-text', variant: 'default', position: 4, props: { title: 'Our approach', body: 'Fresh local ingredients, concise menus, and a calm dining room for neighborhood regulars.' } },
      { id: 'location', type: 'location', variant: 'card', position: 5, props: { title: 'Find us' } },
      { id: 'contact', type: 'contact-form', variant: 'placeholder', position: 6, props: { title: 'Contact Bistro Lumiere' } },
    ],
  },
};

export const chefDemoFrontpage: TenantFrontpageModel = {
  tenant: {
    slug: 'chef',
    locale: 'en',
    displayName: 'Chef Michel Hélène',
    enabledModules: ['frontpage', 'booking', 'notifications', 'quote-request'],
    themePresetId: 'chef',
    layoutConfig: {
      nav: 'centered',
      navSticky: true,
      navTransparency: 'transparent',
      navBrandSlot: 'both',
      navRightText: '06 18 75 47 31',
      navLinks: [
        { label: 'ACCUEIL', href: '/' },
        { label: 'LE CHEF', href: '#about' },
        { label: 'MENUS', href: '#services' },
        { label: 'GALERIE', href: '#gallery' },
        { label: 'PRESSE', href: '#press' },
        { label: 'RÉSERVATION', href: '#reservation' },
      ],
      navSocialLinks: ['https://www.instagram.com/chef_michel_helene/', 'https://www.facebook.com/chefadomicilemichelhelene'],
      hero: 'full-bleed',
      contentWidth: 'wide',
      sectionRhythm: 'spacious',
      sectionBorder: 'thin',
      cardStyle: 'flat',
      headerSpacing: 'margin',
    },
    logoUrl: 'https://chefmichelhelene.com/wp-content/uploads/2025/08/Michel-Helene-noir-scaled.png',
    homeHref: '/t/chef',
  },
  page: {
    id: 'demo-home-chef',
    tenantId: 'demo-chef',
    slug: 'home',
    locale: 'en',
    title: 'Chef à domicile à Paris',
    seo: { title: 'Chef à domicile à Paris– Dîner d’exception | Chef Michel Hélène', description: 'Chef à domicile à Paris pour des dîners d’exception. 17 ans d’expérience en gastronomie, une expérience raffinée et confidentielle.' },
    status: 'published',
    layoutPreset: 'editorial',
    services: [
      { slug: 'menu-degustation', name: 'Menu dégustation', description: 'Un menu gastronomique sur mesure pour une soirée d’exception.', durationMinutes: 120 },
      { slug: 'diner-prive', name: 'Dîner privé', description: 'Un dîner privé clé en main à domicile ou en réception privée.', durationMinutes: 150 },
      { slug: 'reception-privee', name: 'Réception privée', description: 'Une prestation haut de gamme pour vos événements privés.', durationMinutes: 180 },
    ],
    locations: [
      {
        name: 'Chef Michel Hélène',
        address: { street: 'Paris', city: 'Paris', country: 'FR' },
        phone: '+33618754731',
        email: 'contact@chefmichelhelene.com',
      },
    ],
    blocks: [
      {
        id: 'hero',
        type: 'hero',
        variant: 'split-image',
        position: 0,
        props: {
          eyebrow: 'Chef à domicile à Paris',
          headline: 'Chef à domicile à Paris',
          body: 'Chef à domicile à Paris pour des dîners d’exception. 17 ans d’expérience en gastronomie, une expérience raffinée et confidentielle.',
          ctaLabel: 'Réservation',
          secondaryLabel: 'Découvrir le chef',
          secondaryHref: '#about',
          panelLabel: 'Service privé',
          panelTitle: 'Un chef privé à votre service, chez vous ou lors de vos réceptions privées',
          panelBody: 'Une cuisine d’exception, discrète et sur-mesure, pensée pour les moments importants.',
          highlights: ['Menus gastronomiques', 'Service clé en main', 'Paris et île-de-France'],
          panelMeta: ['17 ans d’expérience', 'Chef privé'],
          backgroundImage: 'https://chefmichelhelene.com/wp-content/uploads/2023/12/Chef_a_Domicile_Paris.jpg',
        },
      },
      { id: 'about', type: 'rich-text', variant: 'default', position: 1, props: { eyebrow: 'Le chef', title: 'Le déroulement de votre dîner privé clé en main', body: 'De la préparation au service, tout est orchestré pour vous laisser profiter pleinement de votre soirée.', titleTextStyle: { fontFamily: 'Cormorant Garamond', fontSize: 'clamp(2.8rem, 5.5vw, 5.5rem)', lineHeight: '0.92', textAlign: 'left' }, spacing: { margin: '7rem 0 4rem', padding: '0' } } },
      { id: 'chef', type: 'split-media', variant: 'image-right', position: 2, props: { textTitle: 'Le chef', body: 'Cuisine discrète, précision des cuissons et soin du détail pour une expérience intime et haut de gamme.', imageUrl: 'https://chefmichelhelene.com/wp-content/uploads/2024/02/Chef_Michel_Helene.jpg', alt: 'Chef Michel Hélène', titleTextStyle: { fontFamily: 'Cormorant Garamond', fontSize: 'clamp(2.4rem, 4.5vw, 4.6rem)', lineHeight: '0.95', textAlign: 'left' }, textStyle: { fontSize: '1.08rem', lineHeight: '1.95' }, textSpacing: { margin: '0', padding: '0' }, mediaSpacing: { margin: '0', padding: '0' } } },
      { id: 'services', type: 'service-list', variant: 'cards', position: 3, props: { title: 'Menus gastronomiques à domicile à Paris' } },
      { id: 'reviews', type: 'carousel', variant: 'testimonials', position: 4, props: createCarouselPresetProps('testimonials', { eyebrow: 'Une expérience saluée par mes clients', title: 'Une expérience saluée par mes clients', body: 'Moments partagés autour de la gastronomie.' }) as never },
      { id: 'gallery', type: 'image', variant: 'cover', position: 5, props: { caption: 'Moments partagés autour de la gastronomie', imageUrl: 'https://chefmichelhelene.com/wp-content/uploads/2024/07/presentationviande_chefMichelHelene-scaled.jpg', buttonLabel: 'Voir la galerie', buttonHref: '#gallery' } },
      { id: 'press', type: 'rich-text', variant: 'default', position: 6, props: { title: 'Moments partagés autour de la gastronomie', body: 'Une présence presse, des maisons partenaires et des clients qui reviennent pour l’expérience.', titleTextStyle: { fontFamily: 'Cormorant Garamond', fontSize: 'clamp(2.2rem, 4vw, 4rem)', lineHeight: '0.95', textAlign: 'left' }, spacing: { margin: '6rem 0 3rem', padding: '0' } } },
      { id: 'location', type: 'location', variant: 'card', position: 7, props: { title: 'Dîners privés et prestations à domicile' } },
      { id: 'reservation', type: 'cta', variant: 'banner', position: 8, props: { title: 'Réservez votre prochain dîner avec un chef à domicile à Paris', body: 'Contactez-nous pour imaginer une prestation sur mesure.', label: 'Réservation' } },
    ],
  },
};

export const maisonNoireDemoFrontpage: TenantFrontpageModel = {
  tenant: {
    slug: 'maison-noire',
    locale: 'en',
    displayName: 'Maison Noire',
    enabledModules: ['frontpage', 'booking', 'notifications', 'quote-request'],
    themePresetId: 'luxury-dark-dining',
    layoutConfig: {
      nav: 'overlay',
      navSticky: false,
      hero: 'full-bleed',
      contentWidth: 'full',
      sectionRhythm: 'spacious',
      sectionBorder: 'none',
      cardStyle: 'glass',
      cardRadius: 'round',
    },
    themeOverrides: {
      assets: {
        backgroundImageUrl: '/demo-assets/luxury/page-bg.svg',
        cardBackgroundImageUrl: '/demo-assets/luxury/card-bg.svg',
        heroBackgroundImageUrl: '/demo-assets/luxury/hero-bg.svg',
      },
    },
    logoUrl: '/demo-assets/luxury/logo.svg',
    faviconUrl: '/demo-assets/luxury/favicon.svg',
    homeHref: '/t/maison-noire',
  },
  page: {
    id: 'demo-home-maison-noire',
    tenantId: 'demo-maison-noire',
    slug: 'home',
    locale: 'en',
    title: 'An intimate dining room for exceptional evenings',
    seo: { title: 'An intimate dining room for exceptional evenings', description: 'Luxury restaurant demo tenant with elegant reservations and immersive visual styling.' },
    status: 'published',
    layoutPreset: 'immersive',
    services: [],
    locations: [
      {
        name: 'Maison Noire',
        address: { street: '18 Rue du Faubourg', city: 'Paris', country: 'FR' },
        phone: '+33100000009',
        email: 'reservations@maisonnoire.example',
      },
    ],
    blocks: [
      {
        id: 'hero',
        type: 'hero',
        variant: 'split-image',
        position: 0,
        props: {
          eyebrow: 'Maison Noire',
          headline: 'Refined tasting menus, low light, and impeccable service.',
          body: 'Luxury restaurant demo tenant with elegant reservations, high-touch branding, and immersive visual styling.',
          ctaLabel: 'Reserve now',
          secondaryLabel: 'Explore the menu',
          secondaryHref: '#services',
          panelLabel: 'Dining room',
          panelTitle: 'An intimate evening venue',
          panelBody: 'A dark, editorial public page with flexible blocks and layered visuals.',
          highlights: ['Chef tasting menu', 'Private salon dinners', 'Seasonal wine pairings'],
          panelMeta: ['Paris 1er', 'Open evenings'],
        },
      },
      {
        id: 'carousel',
        type: 'carousel',
        variant: 'testimonials',
        position: 1,
        props: createCarouselPresetProps('testimonials', {
          eyebrow: 'Guest notes',
          title: 'A few reasons guests return',
          body: 'A premium carousel preset for polished social proof and memorable touches.',
        }) as never,
      },
      { id: 'rich', type: 'rich-text', variant: 'default', position: 2, props: { title: 'About us', body: 'An intimate room for exceptional evenings.' } },
      { id: 'location', type: 'location', variant: 'card', position: 3, props: { title: 'Find us' } },
      { id: 'contact', type: 'cta', variant: 'banner', position: 4, props: { title: 'Reserve now', body: 'Choose a convenient time online.', label: 'Reserve now' } },
    ],
  },
};
export function getDemoFrontpageModel(tenantSlug: string): TenantFrontpageModel | null {
  if (tenantSlug === 'chef') return chefDemoFrontpage;
  if (tenantSlug === 'maison-noire') return maisonNoireDemoFrontpage;
  if (tenantSlug === 'bistro-frontpage') return demoFrontpage;
  return null;
}
